- name: Install required packages (APT)
  ansible.builtin.apt:
    name:
      - curl
      - git
      - nfs-common
      - nfs-kernel-server
      - python3-pip
      - python3-kubernetes
      - iptables
      - docker.io 
    state: present
    update_cache: true
  become: true
