################################################################################
# FILE: roles/nfs_netboot/handlers/main.yml
################################################################################
---
- name: Reload NFS exports
  ansible.builtin.command: exportfs -ra
  changed_when: true

- name: Restart NFS server
  ansible.builtin.systemd:
    name: nfs-kernel-server
    state: restarted
