# FILE: roles/setup-nfs-server/tasks/install_nfs_server.yml
---
# Install NFS kernel server package

- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  become: true

- name: Install NFS kernel server
  ansible.builtin.apt:
    name:
      - nfs-kernel-server
      - nfs-common
    state: present
  become: true
